<template>
  <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">
    <blockquote class="blockquote text-center">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Libero nunc consequat interdum varius sit. At tellus at urna condimentum mattis pellentesque id. Leo vel fringilla est ullamcorper eget nulla facilisi. Blandit turpis cursus in hac. Vestibulum lectus mauris ultrices eros in cursus turpis massa. Bibendum enim facilisis gravida neque convallis a cras semper. Pellentesque adipiscing commodo elit at imperdiet. Dignissim diam quis enim lobortis scelerisque fermentum. Pharetra vel turpis nunc eget lorem. In ante metus dictum at tempor commodo ullamcorper a. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Augue neque gravida in fermentum et. Pellentesque habitant morbi tristique senectus. Sed arcu non odio euismod. Id semper risus in hendrerit gravida.

    Facilisis sed odio morbi quis commodo odio aenean. Ac tortor vitae purus faucibus ornare. Duis convallis convallis tellus id interdum velit laoreet. Luctus venenatis lectus magna fringilla. Volutpat sed cras ornare arcu dui vivamus arcu. In nibh mauris cursus mattis molestie. Urna cursus eget nunc scelerisque viverra. Gravida dictum fusce ut placerat orci. Vitae congue mauris rhoncus aenean vel. Nulla at volutpat diam ut venenatis tellus in metus vulputate. Nullam eget felis eget nunc. Cum sociis natoque penatibus et magnis dis. Morbi leo urna molestie at elementum eu facilisis.

    Faucibus interdum posuere lorem ipsum dolor sit amet. Egestas erat imperdiet sed euismod nisi. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Massa tincidunt dui ut ornare lectus sit. Cursus euismod quis viverra nibh cras pulvinar mattis nunc sed. Erat pellentesque adipiscing commodo elit at. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Adipiscing at in tellus integer feugiat scelerisque varius. Lectus mauris ultrices eros in cursus turpis massa. Nulla aliquet enim tortor at auctor urna. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Adipiscing enim eu turpis egestas pretium aenean pharetra magna. Lacus viverra vitae congue eu consequat. Ultricies mi quis hendrerit dolor magna eget est.

    Sit amet nisl suscipit adipiscing bibendum. A lacus vestibulum sed arcu non odio euismod lacinia. Turpis nunc eget lorem dolor sed viverra ipsum nunc. Nunc sed id semper risus in hendrerit. Montes nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Venenatis tellus in metus vulputate. Euismod in pellentesque massa placerat duis ultricies. Purus in massa tempor nec feugiat nisl pretium fusce id. Sagittis id consectetur purus ut faucibus pulvinar elementum integer. Arcu felis bibendum ut tristique et egestas. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Aliquam sem et tortor consequat id porta nibh. Rhoncus mattis rhoncus urna neque viverra. Lacus vel facilisis volutpat est velit egestas dui id ornare. Id leo in vitae turpis massa sed elementum tempus. Interdum posuere lorem ipsum dolor sit amet. Molestie at elementum eu facilisis. Quam elementum pulvinar etiam non. Blandit aliquam etiam erat velit.

    Tristique risus nec feugiat in. Pulvinar etiam non quam lacus suspendisse faucibus interdum. Blandit libero volutpat sed cras ornare arcu dui. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Sit amet venenatis urna cursus. Nam at lectus urna duis convallis convallis tellus id interdum. Mi quis hendrerit dolor magna eget est lorem ipsum. Justo nec ultrices dui sapien eget. Ut faucibus pulvinar elementum integer. Rhoncus dolor purus non enim praesent. Amet consectetur adipiscing elit ut. At consectetur lorem donec massa. At auctor urna nunc id cursus metus aliquam eleifend. Nisl vel pretium lectus quam id leo in vitae turpis.

    Erat pellentesque adipiscing commodo elit at. Justo eget magna fermentum iaculis eu non diam phasellus. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. Tristique senectus et netus et malesuada fames ac turpis. Elit duis tristique sollicitudin nibh sit amet. Felis bibendum ut tristique et egestas quis. Sed velit dignissim sodales ut eu. Risus quis varius quam quisque id diam vel quam. Scelerisque fermentum dui faucibus in ornare quam viverra. Et malesuada fames ac turpis egestas integer eget. Bibendum ut tristique et egestas quis ipsum.

    Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Bibendum at varius vel pharetra vel turpis nunc. At consectetur lorem donec massa sapien faucibus. Velit egestas dui id ornare arcu odio ut. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed. Aliquam etiam erat velit scelerisque in dictum non consectetur a. A iaculis at erat pellentesque adipiscing commodo elit. Elit at imperdiet dui accumsan. Convallis tellus id interdum velit. Ut tortor pretium viverra suspendisse potenti nullam. Bibendum arcu vitae elementum curabitur vitae nunc sed velit. Vulputate eu scelerisque felis imperdiet proin fermentum. Imperdiet massa tincidunt nunc pulvinar. Sed enim ut sem viverra. Vel orci porta non pulvinar neque laoreet. Nisl nisi scelerisque eu ultrices vitae. Libero nunc consequat interdum varius sit. Odio aenean sed adipiscing diam donec adipiscing tristique risus. Nisl suscipit adipiscing bibendum est ultricies integer.

    Leo in vitae turpis massa sed elementum tempus egestas. Arcu dui vivamus arcu felis bibendum ut tristique. Tortor dignissim convallis aenean et tortor. In cursus turpis massa tincidunt. Arcu vitae elementum curabitur vitae. Maecenas accumsan lacus vel facilisis volutpat est velit. Fames ac turpis egestas maecenas pharetra. Velit aliquet sagittis id consectetur purus. Amet justo donec enim diam vulputate ut pharetra sit amet. Ac felis donec et odio. Eget dolor morbi non arcu risus quis varius quam. Magna fermentum iaculis eu non. Nec nam aliquam sem et tortor consequat id. Elementum integer enim neque volutpat ac tincidunt.

    Leo urna molestie at elementum eu facilisis. In tellus integer feugiat scelerisque. Id diam vel quam elementum pulvinar etiam non quam lacus. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Vitae turpis massa sed elementum tempus. Iaculis at erat pellentesque adipiscing commodo elit. Lacus vel facilisis volutpat est velit egestas dui id. In hendrerit gravida rutrum quisque non tellus. Egestas sed sed risus pretium quam vulputate dignissim suspendisse in. Amet justo donec enim diam vulputate ut pharetra. Id eu nisl nunc mi. Consectetur purus ut faucibus pulvinar elementum integer enim neque. Tincidunt arcu non sodales neque sodales ut. Elementum eu facilisis sed odio morbi quis commodo. Ac turpis egestas integer eget aliquet nibh praesent tristique magna. Amet purus gravida quis blandit turpis cursus in.

    Hendrerit dolor magna eget est lorem ipsum dolor. Platea dictumst quisque sagittis purus. Quis lectus nulla at volutpat diam ut. Adipiscing vitae proin sagittis nisl rhoncus. Dolor sed viverra ipsum nunc aliquet. Arcu odio ut sem nulla pharetra diam. Dolor sit amet consectetur adipiscing elit pellentesque. Vitae tempus quam pellentesque nec nam aliquam sem et. Odio pellentesque diam volutpat commodo sed. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam quis. Proin libero nunc consequat interdum varius. Convallis convallis tellus id interdum velit laoreet. Volutpat commodo sed egestas egestas fringilla phasellus faucibus. Risus nullam eget felis eget nunc lobortis. Amet mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Nisl nisi scelerisque eu ultrices vitae auctor eu augue.
    </blockquote>
  </a>
</template>

<script>
export default {
  name: "InfoPage"
}
</script>

<style scoped>

</style>